version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      #- ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_HTTPS_PORT=5254 
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=ThisIsABadWayOfPassword
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/DataProtection-Keys/aspnetapp.pfx 
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=\https\aspnetapp.pfx 
    ports:
      - "5204:80"
      #- "5254:443"
    expose:
      - 5254
  lhci:
    image: patrickhulce/lhci-client:latest
    links:
    - web
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./:/home/:rw
    command: lhci autorun --config ../../lighthouserc.js --collect.settings.chromeFlags="--no-sandbox –-ignore-certificate-errors"
    depends_on:
      - web